DROP SCHEMA IF EXISTS Forager;
CREATE SCHEMA Forager;
USE Forager;

CREATE TABLE Document(
docID INT PRIMARY KEY AUTO_INCREMENT,
docURL VARCHAR(50) UNIQUE NOT NULL,
pageRank FLOAT,
docTitle VARCHAR(50)
);

CREATE TABLE Word(
wordID INT PRIMARY KEY AUTO_INCREMENT,
word VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE Topic(
topicID INT PRIMARY KEY AUTO_INCREMENT,
topidDesc VARCHAR(20) NOT NULL
);

CREATE TABLE defaultUser(
userID INT PRIMARY KEY AUTO_INCREMENT,
IPaddress VARCHAR(15)
);

CREATE TABLE registeredUser(
userID INT PRIMARY KEY REFERENCES defaultUser(userID),
Fname VARCHAR(15),
Minit VARCHAR(1),
Lname VARCHAR(15),
loginID VARCHAR(20) NOT NULL,
userPass VARCHAR(20) NOT NULL,
isAdmin BOOL,
emailID VARCHAR(30)
);

CREATE TABLE Advertisement(
adID INT PRIMARY KEY AUTO_INCREMENT,
imageURL VARCHAR(50) NOT NULL
);

CREATE TABLE UserSession(
userID INT REFERENCES defaultUser(userID),
SessionID INT,
startTime DATETIME,
endTime DATETIME,
CONSTRAINT user_session_pk PRIMARY KEY(userID,SessionID)
);

CREATE TABLE Anchors_From(
sourceID INT REFERENCES Document(docID),
targetID INT REFERENCES Document(docID),
anchorText VARCHAR(50)
);

CREATE TABLE Hits(
docID INT REFERENCES Document(docID),
wordID INT REFERENCES Word(wordID),
wPosition INT,
fontSize INT,
isAnchor BOOL
);

CREATE TABLE docAccessed(
SessionID INT NOT NULL REFERENCES UserSession(SessionID),
docID INT  NOT NULL REFERENCES Document(docID) 
);

CREATE TABLE Likes(
userID INT NOT NULL REFERENCES defaultUser(userID),
topicID INT NOT NULL REFERENCES Topic(topicID)
);

CREATE TABLE docBelongsTo(
docID INT NOT NULL REFERENCES document(docID),
topicID INT NOT NULL REFERENCES Topic(topicID) 
);

CREATE TABLE adBelongsTo(
adID INT NOT NULL REFERENCES Advertisement(adID),
topicID INT NOT NULL REFERENCES Topic(topicID) 
);
